apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-parameters
spec:
  params:
    - name: flags
      type: array       # 设置array类型
    - name: pathToContext
      type: string      # 设置string类型
  steps:
    - name: ls
      image: bash:latest
      command: ["ls","$(params.flags[*])","$(params.pathToContext)"]
      # 执行命令：ls -l -a /tekton/ /workspace

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-parameters
spec:
  taskRef:
    name: task-parameters
  params:
    - name: flags
      value:            # 把多个ls命令的选项一起传递给array类型的params。
        - "-l"
        - "-a"
        - "/tekton/"
    - name: pathToContext
      value: "/workspace"