apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: channel-ping-source
spec:
  schedule: "*/2 * * * *"
  jsonData: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: eventing-channel