apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
    name: eventing-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: eventing-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display