apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-example
spec:
  pipelineRef:
    name: pipeline-example
  params:
    - name: a
      value: "2"
    - name: b
      value: "10"
