apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-hello
spec:
  steps:
    - name: hello
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Hello World!"

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-hello
spec:
  pipelineSpec:                    # 在PipelineRun对象中，通过pipelineSpec字段嵌入Pipeline对象的配置
    tasks:                         # 定义Pipeline中需要执行的Task列表
      - name: hello-one
        taskRef:                   # 引用已存在的Task
          name: task-hello
      - name: hello-two
        taskRef:
          name: task-hello
