apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-hello
spec:
  pipelineSpec:                    # 在PipelineRun对象中，通过pipelineSpec字段嵌入Pipeline对象的配置
    tasks:                         # 定义Pipeline中需要执行的Task列表
      - name: hello-one
        taskSpec:                   # 嵌入Task对象的配置
          params:
            - name: MESSAGE
              default: "Hello World!"
          steps:
            - name: hello
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo "$(params.MESSAGE)"
      - name: hello-two
        taskSpec:
          steps:
            - name: hello
              image: bash:latest
              script: |
                #!/usr/bin/env bash
                echo "Hello World!"
