apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-sa
spec:
  serviceAccountName: docker-git-sa   # 指定Kubernetes集群中的ServiceAccount 
  pipelineRef:
    name: hello-pipeline
