apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  tasks:
    - name: build-to-push
      taskRef:
        name: build-and-push
    - name: task-test
      taskRef:
        name: test

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-sa
spec:
  serviceAccountName: docker-git-sa            # 为Pipeline全局指定ServiceAccount
  serviceAccountNames:                         # 为Pipeline中特定的Task指定ServiceAccount，这将覆盖serviceAccountName的值
    - taskName: build-to-push
      serviceAccountName: build-and-push-sa    
  pipelineRef:
    name: hello-pipeline
