apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-example
spec:
  params:
    - name: a
    - name: b
    - name: fvl
  workspaces:
    - name: filedata
  resources:
    - name: builtImage-p
      type: image
  tasks:
    - name: sum-inputs
      taskRef:
        name: sum
      params:
        - name: a
          value: $(params.a)
        - name: b
          value: $(params.b)
  finally:                             # 开始配置Finally
    - name: finally-one                # 定义一个Task。Finally不支持排序控制，所有Task将被并行执行。 
      taskRef:
        name: print-time               # 引用已存在的Task对象
      params:                          # 引用PipelineParams（可选）。
        - name: fvl
          value: "$(params.fvl)" 
      workspaces:                      # 引用PipelineWorkspaces（可选）。
        - name: digital
          workspace: filedata
      resources:                       # 引用PipelineResources（可选）。注意：Resources不支持from排序子句。
        inputs:
          - name: builtImage
            resource: builtImage-p
    - name: finally-two
      taskRef:
        name: print-time
      params:
        - name: fvl
          value: "$(params.fvl)"
      workspaces:
        - name: digital                                                                           
          workspace: filedata
      resources:
        inputs:
          - name: builtImage
            resource: builtImage-p
      
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sum
spec:
  params:
    - name: a
      type: string
    - name: b
      type: string
  steps:
    - name: sum
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo sum: $(( "$(params.a)" + "$(params.b)" ))

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-time
spec:
  params:
    - name: fvl
      type: string
  workspaces:
    - name: digital
  resources:
    inputs:
      - name: builtImage
        type: image
  steps:
    - name: time
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo $(params.fvl): `date "+%Y-%m-%d %H:%M:%S %Z"` > $(workspaces.digital.path)/file.txt
        echo $(resources.inputs.builtImage.url) >> $(workspaces.digital.path)/file.txt
        cat  $(workspaces.digital.path)/file.txt

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-example
spec:
  pipelineRef:
    name: pipeline-example
  params:
    - name: a
      value: "2"
    - name: b
      value: "10"
    - name: fvl
      value: "Current Time"      
  workspaces:
    - name: filedata
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  resources:
    - name: builtImage-p
      resourceRef:
        name: image-resource
