# 命名空间启用Eventing Injection
apiVersion: v1
kind: Namespace
metadata:
  name: knative-samples
  labels:
       knative-eventing-injection: enabled
---
# 部署Helloworld-go应用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-go
  namespace: knative-samples
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: helloworld-go
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: helloworld-go
          image: docker.io/{username}/helloworld-go

---
# 创建Service，Trigger可以通过Service来确定subscriber
  kind: Service
  apiVersion: v1
  metadata:
    name: helloworld-go
    namespace: knative-samples
  spec:
    selector:
      app: helloworld-go
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# 创建Trigger
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: helloworld-go
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: helloworld-go 
