apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    # 指定Docker registry地址，必须以"tekton.dev/docker-"开头，"*"号部分通过数字或字母填充。
    tekton.dev/docker-0: https://docker.io
    tekton.dev/docker-1: https://gcr.io
# 当通过用户名和密码访问资源时，请使用basic-auth类型。 
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext username>
  password: <cleartext password>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: basic-user-pass

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-task-run-2
spec:
  serviceAccountName: build-bot     # 指定已存在的ServiceAccount。
  taskRef:
    name: build-push

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline
spec:
  serviceAccountName: build-bot     # 指定已存在的ServiceAccount。
  pipelineRef:
    name: demo-pipeline
