apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    # 指定存储库，必须以"tekton.dev/git-"开头，"*"号部分通过数字或字母填充。
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
# 当通过用户名和密码访问资源时，请使用basic-auth类型。
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext username>
  password: <cleartext password>

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-sa
secrets:
  - name: git-secret

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-task-run-2
spec:
  serviceAccountName: git-sa     # 指定已存在的ServiceAccount。
  taskRef:
    name: build-push

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline
spec:
  serviceAccountName: git-sa     # 指定已存在的ServiceAccount。
  pipelineRef:
    name: demo-pipeline