apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  annotations:
    # 指定基于SSH密钥访问Git存储库，必须以"tekton.dev/git-"开头，"*"号部分通过数字或字母填充。
    tekton.dev/git-0: gitlab.com
    # 也可以通过自定义的端口连接存储库。
    tekton.dev/git-1: gitlab.com:10022
# 当通过密钥访问资源时，请使用ssh-auth类型。
type: kubernetes.io/ssh-auth   
data:
  # 指定私钥（必选项）。
  # 指定私钥时需要转换为base64编码（命令：cat id_rsa | base64 -w 0）。  
  ssh-privatekey: <private-key>
  # 指定公钥（可选项）。
  # 指定固定公钥可以提高安全性，可以通过"ssh-keyscan gitlab.com | base64 -w 0"命令获取远程存储库公钥。如果未配置，则盲目接受存储库返回的任何公钥。
  known_hosts: <known-hosts> 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-sa
secrets:
  - name: git-ssh-key            # 指定已存在的Secret。

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-task-run-2
spec:
  serviceAccountName: git-sa     # 指定已存在的ServiceAccount。
  taskRef:
    name: build-push

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline
spec:
  serviceAccountName: git-sa     # 指定已存在的ServiceAccount。
  pipelineRef:
    name: demo-pipelin
