apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-sa
spec:
  serviceAccountName: docker-git-sa  # 指定Kubernetes集群中的ServiceAccount
  taskRef:
    name: task-sa
    kind: Task